name: Build and upload to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.5.3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4.6.1
        with:
          python-version: "3.11"
          architecture: x64

      - name: Build packages
        run: |
          pip install -U pip build
          python -m build sdist wheel
