name: QA

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-qa:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3.1

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4.2.0
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install dependencies (and project)
        run: pip install -e .[lint,scripts]

      - name: Check black formatting
        run: inv lint-black

      - name: Check ruff
        run: inv lint-ruff
